FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Install dependencies
RUN pip install pipenv
#RUN /usr/bin/pip3 install pipenv

#COPY ./app/Pipfile ./app/Pipfile.lock /containerworkdir/ #when using docker build
COPY Pipfile Pipfile.lock /app/
#RUN pipenv install --system --dev --deploy --ignore-pipfile
RUN pipenv install --system --dev --deploy

# Add metadata to the image to describe which port the container is listening on at runtime.
EXPOSE 80
COPY ./app /app/
# Run the specified command within the container.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--forwarded-allow-ips='*'"]
#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

